### ISSUE TITLE
pip install -r requirements.txt fails due to incorrect version specifiers and compatibility issues

### ISSUE THREAD

**Issue by lxy973449157** [SavannahXu79/LinkPrompt#1]
Hello,

I've encountered several issues when trying to install the dependencies listed in the requirements.txt file of this project.

The version specifiers in the requirements.txt file use a single = sign (e.g., absl-py=2.0.0). This is not a valid syntax for pip. The correct syntax should use == (e.g., absl-py==2.0.0).

There are compatibility issues between some of the dependencies' versions. This causes conflicts and prevents successful installation.

The requirements.txt file does not account for different dependencies required for Windows and Linux systems, leading to further installation issues on different platforms.

Steps to Reproduce:

Clone the repository.
Run pip install -r requirements.txt.
Expected Behavior:

All dependencies should be installed successfully without any version conflicts or syntax errors.

Actual Behavior:

The installation fails due to:

Incorrect version specifiers (= instead of ==).
Version conflicts between dependencies.
Platform-specific dependency issues.
Proposed Solution:

Update the requirements.txt file to use the correct version specifier ==.
Review and resolve version conflicts between dependencies.
Consider using environment markers to specify platform-specific dependencies.

**Comment by SavannahXu79** [comment]
Hi, we have fixed the "requirement.txt" and updated the guidance, and you can install all the dependencies now.

**Comment by lxy973449157** [comment]
I noticed that the requirements file is missing a package dependency for scikit-learn

**Comment by SavannahXu79** [comment]
We have updated "requirements.txt", you can also run  `pip install scikit-learn==1.3.0`  to install sklearn in your existing environment. Thanks for your friendly reminder.
