### ISSUE TITLE
Error when loading tokenizer in eval.py

### ISSUE THREAD

**Issue by lxy973449157** [SavannahXu79/LinkPrompt#2]
I encountered an error when running eval.py due to the incorrect path or structure of the model directory. The error occurs at the line where the tokenizer is loaded using AutoTokenizer.from_pretrained('/home/xuyue/Model/roberta-large/'). Could you please update eval.py to ensure the correct path and structure for loading the tokenizer and model?

**Comment by SavannahXu79** [comment]
We have updated the eval.py. Thank you for your friendly reminder.
